package com.rawsmusic

import android.Manifest
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.os.Build
import android.os.Bundle
import android.graphics.RectF
import android.graphics.drawable.BitmapDrawable
import android.view.ScaleGestureDetector
import android.view.View
import android.view.ViewConfiguration
import android.widget.Toast
import androidx.activity.result.contract.ActivityResultContracts
import androidx.core.content.ContextCompat
import androidx.core.view.GravityCompat
import androidx.core.view.WindowCompat
import androidx.drawerlayout.widget.DrawerLayout
import androidx.lifecycle.lifecycleScope
import androidx.navigation.NavController
import androidx.navigation.fragment.NavHostFragment
import coil.Coil
import coil.load
import com.rawsmusic.core.common.base.BaseActivity
import com.rawsmusic.core.common.ext.isDarkMode
import com.rawsmusic.core.common.ext.visible
import com.rawsmusic.core.common.model.PlayState
import com.rawsmusic.core.common.utils.AudioUtils
import com.rawsmusic.core.common.utils.UiUtils
import com.rawsmusic.module.player.PlayerController
import com.rawsmusic.module.player.AudioOutputManager
import com.rawsmusic.module.player.PlayerEventBus
import com.rawsmusic.module.player.PlayerService
import com.rawsmusic.ui.songs.PlayerHolder
import com.rawsmusic.core.ui.animation.ButtonAnimHelper
import com.rawsmusic.core.ui.R as UiR
import com.rawsmusic.core.ui.theme.CoverColorExtractor
import com.rawsmusic.core.ui.theme.ThemeManager
import com.rawsmusic.core.ui.widget.CoverGradientDrawable
import com.rawsmusic.core.ui.widget.SideMenuView
import com.rawsmusic.core.ui.widget.UnifiedPlayerContainer
import com.rawsmusic.databinding.ActivityMainBinding
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlin.math.abs